name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    uses: ./.github/workflows/reusable-playwright.yml
    with:
      run-time-mins: 2
      command: npx playwright test
